---
- name: Install prerequisites for Node.js
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download NodeSource GPG key
  get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /tmp/nodesource.gpg.key
    mode: '0644'

- name: Add NodeSource GPG key
  shell: gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg < /tmp/nodesource.gpg.key
  args:
    creates: /etc/apt/keyrings/nodesource.gpg

- name: Add NodeSource repository (Node.js 20.x LTS)
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main"
    state: present
    filename: nodesource

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Verify Node.js installation
  command: node --version
  register: node_version
  changed_when: false

- name: Verify npm installation
  command: npm --version
  register: npm_version
  changed_when: false

- name: Display Node.js version
  debug:
    msg: "Node.js {{ node_version.stdout }} and npm {{ npm_version.stdout }} installed successfully"

- name: Install Claude Code CLI globally
  npm:
    name: "@anthropic-ai/claude-code"
    global: yes
    state: present

- name: Verify Claude Code installation
  command: claude-code --version
  register: claude_code_version
  changed_when: false
  failed_when: false

- name: Display Claude Code version
  debug:
    msg: "Claude Code {{ claude_code_version.stdout }} installed successfully"
  when: claude_code_version.rc == 0