---
- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade packages
  apt:
    upgrade: "{{ 'dist' if upgrade_dist else 'yes' }}"

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present

- name: Ensure keyring dir exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"