---
- name: Ensure prerequisites for Docker repo
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Ensure keyring dir exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Remove old Docker packages
  apt:
    name:
      - docker
      - docker.io
      - docker-engine
      - containerd
      - runc
    state: absent
  ignore_errors: true

- name: Fetch Docker GPG key (ASCII)
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Convert Docker key to keyring (dearmor)
  command: >
    gpg --dearmor --output /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.gpg

# OPTION A (recommended): no arch filter — simplest and robust
- name: Add Docker apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
    update_cache: yes

- name: Install Docker CE + plugins
  apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  notify: Restart Docker

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add local user(s) to docker group
  user:
    name: "{{ item }}"
    append: true
    groups: docker
  loop: "{{ docker_users | default([]) }}"

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: true
    state: started

# Optional: helpful note
- name: Advise re-login for docker group
  debug:
    msg: "If you added yourself to the docker group, log out/in or run 'newgrp docker' to use Docker without sudo."